# Generated by Django 5.2.6 on 2026-01-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('slide_type', models.CharField(choices=[('IMAGE_ONLY', 'Solo imagen'), ('IMAGE_TEXT', 'Imagen + texto')], default='IMAGE_TEXT', max_length=20)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_slides/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hero_slides/logos/')),
                ('cta_text', models.CharField(blank=True, max_length=40)),
                ('cta_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
